/*
 * The MIT License
 *
 * Copyright 2023 ACER.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package esbam.canoa123.views.telaviagemviews;

import esbam.canoa123.controll.PassageirosController;
import esbam.canoa123.controll.PassagensController;
import esbam.canoa123.model.Passageiros;
import esbam.canoa123.model.Passagens;
import esbam.canoa123.views.TelaPrincipal;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonny Nunes Viana
 */
public class TelaViagem extends javax.swing.JFrame {
    private javax.swing.table.DefaultTableModel table;
    private int rowIDPassagem = 0;

    public TelaViagem() {
        initComponents();
        componetesInit();
        executeLista();
        imagemLupa();
    }
    
    // ************************************************************************************
    
    /**
     * 
     */
    private void componetesInit(){
        table = (javax.swing.table.DefaultTableModel) tblPassageiroPassagem.getModel();
    }
    
    /**
     * 
     */
    private void executeLista(){
        addRowsTable(new PassageirosController().listaPassageiros(), new PassagensController().listaPassagens());
    }
    
    /**
     * 
     */
    private void imagemLupa(){
        ImageIcon imgIcon = new ImageIcon();
        imgIcon.setImage(altDimen("lupaPesquisa", lblimgLupa));
        lblimgLupa.setText("");
        lblimgLupa.setIcon(imgIcon);
        lblimgLupa.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPassageiroPassagem = new javax.swing.JTable();
        paneSubMain = new javax.swing.JPanel();
        paneInputsPassageiro = new javax.swing.JPanel();
        txtIDPassageiro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCpfPassageiro = new javax.swing.JTextField();
        txtSexoPassageiro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefonePassageiro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNomePassageiro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        paneInputsPassagem = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDPassagem = new javax.swing.JTextField();
        txtOrigemPassagem = new javax.swing.JTextField();
        txtDestinoPassagem = new javax.swing.JTextField();
        txtValorPassagem = new javax.swing.JTextField();
        txtDataPassagem = new javax.swing.JTextField();
        btnCancelaPassagem = new javax.swing.JButton();
        btnAtribuirPassagem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCategoriaPassagem = new javax.swing.JTextField();
        txtPesquisaNome = new javax.swing.JTextField();
        lblimgLupa = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnVolta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Viagens");

        paneMain.setBackground(new java.awt.Color(60, 14, 64));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblPassageiroPassagem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblPassageiroPassagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Passageiro", "Nome", "Cpf", "Sexo", "Telefone", "Id_Passagem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPassageiroPassagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPassageiroPassagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPassageiroPassagem);
        if (tblPassageiroPassagem.getColumnModel().getColumnCount() > 0) {
            tblPassageiroPassagem.getColumnModel().getColumn(0).setMinWidth(15);
            tblPassageiroPassagem.getColumnModel().getColumn(1).setMinWidth(50);
            tblPassageiroPassagem.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblPassageiroPassagem.getColumnModel().getColumn(5).setMinWidth(15);
        }

        paneSubMain.setBackground(new java.awt.Color(60, 14, 78));
        paneSubMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paneInputsPassageiro.setBackground(new java.awt.Color(60, 14, 78));
        paneInputsPassageiro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIDPassageiro.setEditable(false);
        txtIDPassageiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIDPassageiro.setForeground(new java.awt.Color(0, 0, 0));
        txtIDPassageiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel3.setText("Cpf");

        txtCpfPassageiro.setEditable(false);
        txtCpfPassageiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCpfPassageiro.setForeground(new java.awt.Color(0, 0, 0));
        txtCpfPassageiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtSexoPassageiro.setEditable(false);
        txtSexoPassageiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSexoPassageiro.setForeground(new java.awt.Color(0, 0, 0));
        txtSexoPassageiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel4.setText("Sexo");

        txtTelefonePassageiro.setEditable(false);
        txtTelefonePassageiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefonePassageiro.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonePassageiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel5.setText("Telefone");

        txtNomePassageiro.setEditable(false);
        txtNomePassageiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomePassageiro.setForeground(new java.awt.Color(0, 0, 0));
        txtNomePassageiro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel11.setText("Nome");

        javax.swing.GroupLayout paneInputsPassageiroLayout = new javax.swing.GroupLayout(paneInputsPassageiro);
        paneInputsPassageiro.setLayout(paneInputsPassageiroLayout);
        paneInputsPassageiroLayout.setHorizontalGroup(
            paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsPassageiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputsPassageiroLayout.createSequentialGroup()
                        .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpfPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSexoPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneInputsPassageiroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIDPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInputsPassageiroLayout.createSequentialGroup()
                        .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneInputsPassageiroLayout.setVerticalGroup(
            paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInputsPassageiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexoPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneInputsPassagem.setBackground(new java.awt.Color(60, 14, 78));
        paneInputsPassagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel6.setText("ID");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel7.setText("Origem");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel8.setText("Destino");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel9.setText("Data");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel10.setText("Valor");

        txtIDPassagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIDPassagem.setForeground(new java.awt.Color(0, 0, 0));
        txtIDPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtOrigemPassagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtOrigemPassagem.setForeground(new java.awt.Color(0, 0, 0));
        txtOrigemPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtDestinoPassagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDestinoPassagem.setForeground(new java.awt.Color(0, 0, 0));
        txtDestinoPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtValorPassagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorPassagem.setForeground(new java.awt.Color(0, 0, 0));
        txtValorPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtDataPassagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDataPassagem.setForeground(new java.awt.Color(0, 0, 0));
        txtDataPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnCancelaPassagem.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCancelaPassagem.setForeground(new java.awt.Color(255, 96, 83));
        btnCancelaPassagem.setText("Cancelar");
        btnCancelaPassagem.setToolTipText("Cancelar uma passagem");
        btnCancelaPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelaPassagem.setBorderPainted(false);
        btnCancelaPassagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelaPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaPassagemActionPerformed(evt);
            }
        });

        btnAtribuirPassagem.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnAtribuirPassagem.setForeground(new java.awt.Color(255, 96, 83));
        btnAtribuirPassagem.setText("Atribuir");
        btnAtribuirPassagem.setToolTipText("Atribuir uma passagem");
        btnAtribuirPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAtribuirPassagem.setBorderPainted(false);
        btnAtribuirPassagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel1.setText("Categoria");

        txtCategoriaPassagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCategoriaPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout paneInputsPassagemLayout = new javax.swing.GroupLayout(paneInputsPassagem);
        paneInputsPassagem.setLayout(paneInputsPassagemLayout);
        paneInputsPassagemLayout.setHorizontalGroup(
            paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                        .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOrigemPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtDestinoPassagem)))
                    .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIDPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                        .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                                .addComponent(txtDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                        .addGap(0, 101, Short.MAX_VALUE)
                        .addComponent(btnAtribuirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                        .addComponent(txtCategoriaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneInputsPassagemLayout.setVerticalGroup(
            paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneInputsPassagemLayout.createSequentialGroup()
                        .addComponent(txtOrigemPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDestinoPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(paneInputsPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtribuirPassagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtPesquisaNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisaNome.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisaNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPesquisaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaNomeKeyReleased(evt);
            }
        });

        lblimgLupa.setForeground(java.awt.SystemColor.textHighlightText);
        lblimgLupa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimgLupa.setText("IMG");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.SystemColor.textHighlightText);
        jLabel12.setText("Pesquisa pelo nome");

        javax.swing.GroupLayout paneSubMainLayout = new javax.swing.GroupLayout(paneSubMain);
        paneSubMain.setLayout(paneSubMainLayout);
        paneSubMainLayout.setHorizontalGroup(
            paneSubMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSubMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSubMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneSubMainLayout.createSequentialGroup()
                        .addComponent(paneInputsPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paneInputsPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneSubMainLayout.createSequentialGroup()
                        .addComponent(lblimgLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneSubMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneSubMainLayout.setVerticalGroup(
            paneSubMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSubMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSubMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneInputsPassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneInputsPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneSubMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneSubMainLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneSubMainLayout.createSequentialGroup()
                        .addComponent(lblimgLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        btnVolta.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnVolta.setForeground(new java.awt.Color(255, 96, 83));
        btnVolta.setText("Volta");
        btnVolta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVolta.setBorderPainted(false);
        btnVolta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addComponent(btnVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(paneSubMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneSubMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ************************************************************************************
    // EVENTOS
    private void btnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaActionPerformed
        TelaPrincipal telPrincipal = new TelaPrincipal();
        telPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltaActionPerformed

    private void tblPassageiroPassagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPassageiroPassagemMouseClicked
        int row = tblPassageiroPassagem.getSelectedRow();
        txtIDPassageiro.setText(table.getValueAt(row, 0).toString());
        txtNomePassageiro.setText(table.getValueAt(row, 1).toString());
        txtCpfPassageiro.setText(table.getValueAt(row, 2).toString());
        txtSexoPassageiro.setText(table.getValueAt(row, 3).toString());
        txtTelefonePassageiro.setText(table.getValueAt(row, 4).toString());
        int id = (table.getValueAt(row, 5).toString().equalsIgnoreCase("null")) ? 0 : Integer.parseInt(table.getValueAt(row, 5).toString());
        try {
            Passagens passagem = new PassagensController().joinTableRCC(id);
            txtIDPassagem.setText(Integer.toString(passagem.getId()));
            txtOrigemPassagem.setText(passagem.getId_rota().getOrigem().getLocalidade());
            txtDestinoPassagem.setText(passagem.getId_rota().getDestino().getLocalidade());
            txtValorPassagem.setText(Float.toString(passagem.getId_rota().getValor()));
            txtCategoriaPassagem.setText(passagem.getId_rota().getCategoria().getNome());
            txtDataPassagem.setText(new SimpleDateFormat("dd/MM/yyyy").format(passagem.getDataCompra()));
        } catch (Exception e) {
            excluirCamposPassagem();
            JOptionPane.showMessageDialog(this, "Passageiro não possue passagem", "Passagem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tblPassageiroPassagemMouseClicked

    private void txtPesquisaNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaNomeKeyReleased
        if(evt.getKeyCode() == evt.VK_ENTER){
            pesquisa();
        }
    }//GEN-LAST:event_txtPesquisaNomeKeyReleased

    private void btnCancelaPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaPassagemActionPerformed
        /*
        if(tblPassageiroPassagem.getSelectedRow() != (-1)){
            String id = tblCidades.getValueAt(tblCidades.getSelectedRow(), 0).toString();
            String localidade = tblCidades.getValueAt(tblCidades.getSelectedRow(), 1).toString();
            String estado = tblCidades.getValueAt(tblCidades.getSelectedRow(), 2).toString();
            int respota = JOptionPane.showInternalConfirmDialog(null, "Deseja excluir\n\n" + "Id: " + id + "\n" + "Localidade: " + localidade + "\n" + "Estado: "+ estado + "\n\n", "Deletando", JOptionPane.YES_NO_OPTION);
            if(respota == 0){
                excluirCidade();
                excluirRows();
                executeLista();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
        }
        */
    }//GEN-LAST:event_btnCancelaPassagemActionPerformed
    
    // ************************************************************************************
    
    /**
     * 
     * @param nomeImg
     * @param lbl
     * @return 
     */
    private java.awt.Image altDimen(String nomeImg, javax.swing.JLabel lbl) {
        BufferedImage img = null;
        try {
            img = javax.imageio.ImageIO.read(new java.io.File(String.format("C:\\Projetos\\Gerecionamento\\Canoa123\\src\\esbam\\canoa123\\img\\%s.png", nomeImg)));
        } catch (java.io.IOException ex) {
            lbl.setAlignmentX(CENTER_ALIGNMENT);
            lbl.setAlignmentY(CENTER_ALIGNMENT);
            lbl.setText("<html>Erro ao carregar imagem</html>");
            return null;
        }
        java.awt.Image imageDimensionada = img.getScaledInstance(lbl.getWidth() - 2, lbl.getHeight() - 2, java.awt.Image.SCALE_SMOOTH);
        return imageDimensionada;
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaViagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtribuirPassagem;
    private javax.swing.JButton btnCancelaPassagem;
    private javax.swing.JButton btnVolta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimgLupa;
    private javax.swing.JPanel paneInputsPassageiro;
    private javax.swing.JPanel paneInputsPassagem;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPanel paneSubMain;
    private javax.swing.JTable tblPassageiroPassagem;
    private javax.swing.JTextField txtCategoriaPassagem;
    private javax.swing.JTextField txtCpfPassageiro;
    private javax.swing.JTextField txtDataPassagem;
    private javax.swing.JTextField txtDestinoPassagem;
    private javax.swing.JTextField txtIDPassageiro;
    private javax.swing.JTextField txtIDPassagem;
    private javax.swing.JTextField txtNomePassageiro;
    private javax.swing.JTextField txtOrigemPassagem;
    private javax.swing.JTextField txtPesquisaNome;
    private javax.swing.JTextField txtSexoPassageiro;
    private javax.swing.JTextField txtTelefonePassageiro;
    private javax.swing.JTextField txtValorPassagem;
    // End of variables declaration//GEN-END:variables

    // METODOS
    private void excluirRows(){
        while(table.getRowCount() != 0){
            table.removeRow(0);
        }
    }
    
    /**
     * 
     */
    private void excluirCamposPassagem(){
        txtIDPassagem.setText("");
        txtOrigemPassagem.setText("");
        txtDestinoPassagem.setText("");
        txtValorPassagem.setText("");
        txtCategoriaPassagem.setText("");
        txtDataPassagem.setText("");
    }
    
    /**
     * 
     */
    private void pesquisa(){
        try {
            String nome = txtPesquisaNome.getText();
            excluirRows();
            addRowsTable(new PassageirosController().listNomePassageiros(nome), new PassagensController().listaPassagens());
        } catch (Exception e) {
            excluirRows();
            executeLista();
        }
    }
    
    /**
     * 
     * @param passageiro
     * @param passagem 
     */
    private void addRowsTable(ArrayList<Passageiros> passageiro, ArrayList<Passagens> passagem){
        passageiro.forEach((v) -> {
                int i = table.getRowCount();
                boolean comparatorID = false;
                String semPassagem = "NULL";
                while(comparatorID != true){
                    if(rowIDPassagem == passagem.size() || comparatorID){
                        break;
                    }
                    rowIDPassagem++;
                    comparatorID = passageiro.get(i).getId() == passagem.get(rowIDPassagem - 1).getId_passageiro().getId();
                }
                table.addRow(new Object[] {
                    passageiro.get(i).getId(),
                    passageiro.get(i).getNome(),
                    passageiro.get(i).getCpf(),
                    passageiro.get(i).getSexo(),
                    passageiro.get(i).getTelefone(),
                    (comparatorID) ? passagem.get(rowIDPassagem - 1).getId() : semPassagem
                });
            rowIDPassagem = 0;
        });
    }
}