/*
 * The MIT License
 *
 * Copyright 2023 ACER.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package esbam.canoa123.views.telaloginviews;

import esbam.canoa123.security.SecurityDada;
import esbam.canoa123.controll.UsuariosController;
import esbam.canoa123.views.TelaPrincipal;

import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Cursor;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author ACER
 */
public class TelaLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        executeComponentInit();
        interfaceMainInit();
        initAcessos();
    }
    
    //INICIALIZADORES
    private void executeComponentInit(){
        jrbUser.setSelected(true);     
        lblImgUser.setText("");
        ImageIcon newImg = new ImageIcon();
        newImg.setImage(altDimen("controllerUser", lblImgUser));
        lblImgUser.setIcon(newImg);
    }
    
    private void interfaceMainInit(){
        this.setResizable(false);
    }
    
    private void initAcessos(){
        new UsuariosController().resetaAcessos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupAdmUser = new javax.swing.ButtonGroup();
        paneMain = new javax.swing.JPanel();
        jrbUser = new javax.swing.JRadioButton();
        jrbAdm = new javax.swing.JRadioButton();
        paneLogar = new javax.swing.JPanel();
        lblAcessoString = new javax.swing.JLabel();
        lblAcessoNumber = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        btnAdcionarUser = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        lblImgUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneMain.setBackground(new java.awt.Color(59, 10, 58));

        btGroupAdmUser.add(jrbUser);
        jrbUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbUser.setForeground(new java.awt.Color(0, 0, 0));
        jrbUser.setText("User");
        jrbUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jrbUser.setBorderPainted(true);
        jrbUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbUser.setFocusPainted(false);
        jrbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbUserMouseClicked(evt);
            }
        });

        btGroupAdmUser.add(jrbAdm);
        jrbAdm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbAdm.setForeground(new java.awt.Color(0, 0, 0));
        jrbAdm.setText("Adm");
        jrbAdm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jrbAdm.setBorderPainted(true);
        jrbAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrbAdm.setFocusPainted(false);
        jrbAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbAdmMouseClicked(evt);
            }
        });

        paneLogar.setBackground(new java.awt.Color(60, 28, 99));
        paneLogar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAcessoString.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAcessoString.setForeground(java.awt.SystemColor.textHighlightText);
        lblAcessoString.setText("Login");

        lblAcessoNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAcessoNumber.setForeground(java.awt.SystemColor.textHighlightText);
        lblAcessoNumber.setText("Senha");

        btnEntrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        txtLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnAdcionarUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdcionarUser.setForeground(new java.awt.Color(0, 0, 0));
        btnAdcionarUser.setText("Adicionar user");
        btnAdcionarUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdcionarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdcionarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcionarUserActionPerformed(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(0, 0, 0));
        txtSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout paneLogarLayout = new javax.swing.GroupLayout(paneLogar);
        paneLogar.setLayout(paneLogarLayout);
        paneLogarLayout.setHorizontalGroup(
            paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLogarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdcionarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneLogarLayout.createSequentialGroup()
                        .addGroup(paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAcessoNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(lblAcessoString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtSenha))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneLogarLayout.setVerticalGroup(
            paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLogarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcessoString, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAcessoNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(paneLogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdcionarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblImgUser.setForeground(java.awt.SystemColor.textHighlightText);
        lblImgUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgUser.setText("imgUser");

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneLogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addComponent(jrbAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbUser))
                    .addComponent(lblImgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneLogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // EVENTOS DOS COMPONENTES
    private void jrbAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbAdmMouseClicked
        if(!evt.isConsumed()){
            lblAcessoNumber.setText("Código");
        }
    }//GEN-LAST:event_jrbAdmMouseClicked

    private void jrbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbUserMouseClicked
        if(!evt.isConsumed()){
            lblAcessoNumber.setText("Senha");
        }
    }//GEN-LAST:event_jrbUserMouseClicked

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String login = txtLogin.getText();
        String senha = txtSenha.getText();
        if(jrbAdm.isSelected()){
            // ADM
            abrirJanelaPrincipal(login, senha, jrbAdm);
        }else{
            // USER
            abrirJanelaPrincipal(login, senha, jrbUser);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnAdcionarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarUserActionPerformed
        String login = txtLogin.getText();
        String senha = txtSenha.getText();
        if(jrbAdm.isSelected()){
            abrirJanelaUsuario(login, senha);
        }else{
            JOptionPane.showMessageDialog(this, "Selecione: entrar como Adm!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAdcionarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }
    
    // *****************************************************************************
    // MÉTODOS
    
    /**
     * 
     * @param login
     * @param senha
     * @param jrb 
     */
    private void abrirJanelaPrincipal(String login, String senha, javax.swing.JRadioButton jrb){
        senha = new SecurityDada().criptString(senha);
        if(!menssagemAlertaCampos(jrb)){
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            UsuariosController userControll = new UsuariosController();
            if(userControll.usuarioLoginAcesso(userControll.usuarioLoginSenha(login, senha), jrb.getText())){
                TelaPrincipal telPrin = new TelaPrincipal();
                this.dispose();
                telPrin.setVisible(true);
            }else{
            JOptionPane.showMessageDialog(this, "Dados do "+jrb.getText()+" inválidos!", "Atenção", JOptionPane.WARNING_MESSAGE);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        }   
    }
    
    /**
     * Método de acesso a janela de usuários, do qual somente o adm pode acessar.
     * @param login
     * @param senha 
     */
    private void abrirJanelaUsuario(String login, String senha){
        senha = new SecurityDada().criptString(senha);
        if(!menssagemAlertaCampos(jrbAdm)){
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            UsuariosController userControll = new UsuariosController();
            if(userControll.usuarioLoginAcesso(userControll.usuarioLoginSenha(login, senha), "adm")){
                TelaAddUser telUser = new TelaAddUser();
                telUser.lblNomeAdm.setText("Adm: " + userControll.usuarioLoginSenha(login, senha).getNome());
                telUser.setVisible(true);
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }else{
                JOptionPane.showMessageDialog(this, "Dados do adm inválidos!", "Atenção", JOptionPane.WARNING_MESSAGE);
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        }
    }
    
    /**
     * 
     * @param jrb
     * @return 
     */
    private boolean menssagemAlertaCampos(javax.swing.JRadioButton jrb){
        if(new UsuariosController().verificaNullCampos(txtLogin.getText(), txtSenha.getText())){
            JOptionPane.showMessageDialog(this, "Preencha os campos do "+jrb.getText()+"!", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }else{
            return false;
        }
    }
    
    // *****************************************************************************
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGroupAdmUser;
    private javax.swing.JButton btnAdcionarUser;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JRadioButton jrbAdm;
    private javax.swing.JRadioButton jrbUser;
    private javax.swing.JLabel lblAcessoNumber;
    private javax.swing.JLabel lblAcessoString;
    private javax.swing.JLabel lblImgUser;
    private javax.swing.JPanel paneLogar;
    private javax.swing.JPanel paneMain;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    // *****************************************************************************
    // MODIFICADORES
    
    /**
     * 
     * @param nomeImg
     * @param lbl
     * @return 
     */
    private java.awt.Image altDimen(String nomeImg, javax.swing.JLabel lbl) {
        BufferedImage img = null;
        try {
            img = javax.imageio.ImageIO.read(new java.io.File(String.format("C:\\Projetos\\Gerecionamento\\Canoa123\\src\\esbam\\canoa123\\img\\%s.png", nomeImg)));
        } catch (java.io.IOException ex) {
            lbl.setAlignmentX(CENTER_ALIGNMENT);
            lbl.setAlignmentY(CENTER_ALIGNMENT);
            lbl.setText("<html>Erro ao carregar imagem</html>");
            return null;
        }
        java.awt.Image imageDimensionada = img.getScaledInstance(lbl.getWidth() - 5, lbl.getHeight() - 5, java.awt.Image.SCALE_SMOOTH);
        return imageDimensionada;
    }
}
