package esbam.canoa123.views.telacadastroviews;

import esbam.canoa123.views.TelaPrincipal;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class TelaDeRegistro extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeRegistro
     */
    public TelaDeRegistro() {
        initComponents();
        addItem();
        this.setResizable(false);
    }
    
    // INICIALIZADORES
    private void addItem(){
        cmbItensRegistro.addItem("Barcos");
        cmbItensRegistro.addItem("Rota");
        cmbItensRegistro.addItem("Cidade");
        cmbItensRegistro.addItem("Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneMain = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        cmbItensRegistro = new javax.swing.JComboBox<>();
        paneRodape = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar");

        paneMain.setBackground(new java.awt.Color(101, 32, 91));
        paneMain.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selecione a entidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), java.awt.SystemColor.textHighlightText)); // NOI18N

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setToolTipText("");
        lblImage.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(179, 39, 39), new java.awt.Color(255, 179, 64)));
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmbItensRegistro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbItensRegistro.setForeground(new java.awt.Color(0, 0, 0));
        cmbItensRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cmbItensRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbItensRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbItensRegistro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItensRegistroItemStateChanged(evt);
            }
        });

        paneRodape.setBackground(new java.awt.Color(50, 35, 150));

        btnVoltar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 96, 83));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnVoltar.setBorderPainted(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 96, 83));
        btnRegistrar.setText("Prosseguir");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneRodapeLayout = new javax.swing.GroupLayout(paneRodape);
        paneRodape.setLayout(paneRodapeLayout);
        paneRodapeLayout.setHorizontalGroup(
            paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addContainerGap())
        );
        paneRodapeLayout.setVerticalGroup(
            paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRodapeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbItensRegistro, 0, 174, Short.MAX_VALUE)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
            .addComponent(paneRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbItensRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(paneRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // EVENTOS
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaPrincipal telaPrin = new TelaPrincipal();
        this.dispose();
        telaPrin.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(!cmbItensRegistro.getSelectedItem().toString().equals("Selecione")){
            TelaCadastrar telaCasd = new TelaCadastrar(cmbItensRegistro.getSelectedItem().toString());
            this.dispose();
            telaCasd.setVisible(true);
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um item!", "Selecione", javax.swing.JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // EVENTO QUE VAI VERIFICAR O ESTADO DOS ITENS (A TROCA) E REALIZAR ALGUMA COISA (A SELEÇÃO DA IMAGEM)
    private void cmbItensRegistroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItensRegistroItemStateChanged
        String regEscolha = cmbItensRegistro.getSelectedItem().toString();
        lblImage.setIcon(
        (regEscolha.equalsIgnoreCase("Barcos")) ? 
        alterarImg(1) : 
        (regEscolha.equalsIgnoreCase("Rota")) ?
        alterarImg(2) : 
        (regEscolha.equalsIgnoreCase("Cidade")) ?
        alterarImg(3) : 
        (regEscolha.equalsIgnoreCase("Categoria")) ?
        alterarImg(4) : null
        );
        lblImage.updateUI();
    }//GEN-LAST:event_cmbItensRegistroItemStateChanged

    /**
     * 
     * @param indexIem
     * @return 
     */
    // METODO DE ESCOLHA DA IMAGEM
    private ImageIcon alterarImg(int indexIem){
        ImageIcon newImg = new ImageIcon();        
        switch (indexIem) {
            case 1: 
                newImg.setImage(altDimen("barco"));
                return newImg;  
            case 2:
                newImg.setImage(altDimen("rota"));
                return newImg;   
            case 3:
                newImg.setImage(altDimen("cidade"));
                return newImg;
            case 4:
                newImg.setImage(altDimen("categoria"));
                return newImg;
            default:
                return null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaDeRegistro().setVisible(true);
        });
    }
    
    // MODIFICADORES
    private java.awt.Image altDimen(String nomeImg){
        BufferedImage img = null;
        try{
            img = javax.imageio.ImageIO.read(new java.io.File(String.format
            ("C:\\Projetos\\Gerecionamento\\Canoa123\\src\\esbam\\canoa123\\img\\%s.png", nomeImg)));
        }catch(java.io.IOException ex){
            lblImage.setAlignmentX(CENTER_ALIGNMENT);
            lblImage.setAlignmentY(CENTER_ALIGNMENT);
            lblImage.setText("<html>Erro ao carregar imagem</html>");
            return null;
        }
        // CONFIGURAR A IMAGE E ATRIBUI-LA AO OBJETO DA CLASSE IMAGE
        // O TERCEIRO PARAMETRO DO METODO "GETSCALEDINSTANCE" E DIZER QUE O NOVO DIMENSIONAMENTO SEJA SUAVE
        java.awt.Image imageDimensionada = img.getScaledInstance(lblImage.getWidth() - 12, lblImage.getHeight() - 12, java.awt.Image.SCALE_SMOOTH);      
        return imageDimensionada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbItensRegistro;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPanel paneRodape;
    // End of variables declaration//GEN-END:variables
}
