package esbam.canoa123.views.telacadastroviews;

// CLASSES (JAVA)
import esbam.canoa123.controll.CategoriasController;
import esbam.canoa123.controll.CidadesController;
import java.awt.CardLayout;

// CALSSES (ESBAM)
import esbam.canoa123.register.RegistraDados;
import esbam.canoa123.controll.bussines.RestringeCampoText;
import esbam.canoa123.controll.bussines.ValideCampoText;
import javax.swing.JOptionPane;

public class TelaCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form CadastarBarcos
     */
    public TelaCadastrar() {
        initComponents();
    }

    public TelaCadastrar(String nomeObjeto) {
        initComponents();
        registroEscolhido(nomeObjeto);
        addSelectItem();
    }

    /**
     * 
     */
    // INICIALIZADORES
    private void addSelectItem(){    
        new CidadesController().listaCidades().forEach((v) -> { // TRAZENDO A LISTA CONSULTADA DAS CIDADES REGISTRADAS
            jcbDestino.addItem(v.getLocalidade());
            jcbOrigem.addItem(v.getLocalidade());
        });
        if(jcbDestino.getItemCount() > 2){ // INICIANDO O ITEM COM OS DOIS PRIMEIROS (IGNORANDO O "SELECIONE")
            txtOrigemRota.setText(jcbOrigem.getItemAt(1));
            txtDestinoRota.setText(jcbDestino.getItemAt(2));            
            jcbDestino.setSelectedIndex(2);
            jcbOrigem.setSelectedIndex(1);
        }
        new CategoriasController().lista().forEach((v) -> { jcbCategoria.addItem(v.getNome()); });
        if(jcbCategoria.getItemCount() > 1){
            txtCategoriaRota.setText(jcbCategoria.getItemAt(1));
            jcbCategoria.setSelectedIndex(1);
        }
    }
    
    /**
     * 
     * @param nome 
     */
    // ESCOLHA DOS PAINEIS PELO ITEM SELECIONADO
    private void registroEscolhido(String nome) {
        CardLayout cl = (CardLayout) this.paneMain.getLayout();
        try {
            if (nome.equalsIgnoreCase("barco")) {
                cl.show(this.paneMain, "paneOptionCadastroBarco");
            } else if (nome.equalsIgnoreCase("rota")) {
                cl.show(this.paneMain, "paneOptionCadastroRota");
            } else if (nome.equalsIgnoreCase("cidade")){
                cl.show(this.paneMain, "paneOptionCadastroCidade");
            } else if (nome.equalsIgnoreCase("categoria")){
                cl.show(this.paneMain, "paneOptionCadastroCategoria");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneMain = new javax.swing.JPanel();
        paneOptionCadastroBarco = new javax.swing.JPanel();
        paneInputsBarco = new javax.swing.JPanel();
        txtNomeBarco = new javax.swing.JTextField();
        txtCapacidadeBarco = new javax.swing.JTextField();
        lblNomeBarco = new javax.swing.JLabel();
        lblCapacidadeBarco = new javax.swing.JLabel();
        lblTituloBarco = new javax.swing.JLabel();
        paneOptionCadastroRota = new javax.swing.JPanel();
        lblTituloRota = new javax.swing.JLabel();
        paneInputsRota = new javax.swing.JPanel();
        lblValorRota = new javax.swing.JLabel();
        txtValorRota = new javax.swing.JFormattedTextField();
        txtOrigemRota = new javax.swing.JTextField();
        lblOrigemRota = new javax.swing.JLabel();
        txtDestinoRota = new javax.swing.JTextField();
        lblDestinoRota = new javax.swing.JLabel();
        jcbDestino = new javax.swing.JComboBox<>();
        jcbOrigem = new javax.swing.JComboBox<>();
        lblCategoriaRota = new javax.swing.JLabel();
        txtCategoriaRota = new javax.swing.JTextField();
        jcbCategoria = new javax.swing.JComboBox<>();
        paneOptionCadastroCidade = new javax.swing.JPanel();
        lblTituloCidade = new javax.swing.JLabel();
        paneInputsCidade = new javax.swing.JPanel();
        lblEstadoCidade = new javax.swing.JLabel();
        lblCidadeCidade = new javax.swing.JLabel();
        txtEstadoCidade = new javax.swing.JTextField();
        txtCidadeCidade = new javax.swing.JTextField();
        paneOptionCadastroCategoria = new javax.swing.JPanel();
        lblTituloCategoria = new javax.swing.JLabel();
        paneInputsCategoria = new javax.swing.JPanel();
        lblNomeCategoria = new javax.swing.JLabel();
        txtNomeCategoria = new javax.swing.JTextField();
        paneRodape = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar");

        paneMain.setBackground(new java.awt.Color(27, 2, 48));
        paneMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneMain.setLayout(new java.awt.CardLayout());

        paneOptionCadastroBarco.setBackground(new java.awt.Color(50, 7, 88));

        paneInputsBarco.setBackground(new java.awt.Color(59, 12, 108));

        txtNomeBarco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomeBarco.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeBarco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNomeBarco.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNomeBarco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeBarcoKeyTyped(evt);
            }
        });

        txtCapacidadeBarco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCapacidadeBarco.setForeground(new java.awt.Color(0, 0, 0));
        txtCapacidadeBarco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCapacidadeBarco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadeBarcoKeyTyped(evt);
            }
        });

        lblNomeBarco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeBarco.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeBarco.setText("Capacidade");

        lblCapacidadeBarco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCapacidadeBarco.setForeground(new java.awt.Color(255, 255, 255));
        lblCapacidadeBarco.setText("Nome");

        javax.swing.GroupLayout paneInputsBarcoLayout = new javax.swing.GroupLayout(paneInputsBarco);
        paneInputsBarco.setLayout(paneInputsBarcoLayout);
        paneInputsBarcoLayout.setHorizontalGroup(
            paneInputsBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsBarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCapacidadeBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomeBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCapacidadeBarco)
                    .addComponent(txtNomeBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        paneInputsBarcoLayout.setVerticalGroup(
            paneInputsBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneInputsBarcoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(paneInputsBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidadeBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidadeBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        lblTituloBarco.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTituloBarco.setForeground(new java.awt.Color(255, 96, 83));
        lblTituloBarco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloBarco.setText("Cadastrar Barco");

        javax.swing.GroupLayout paneOptionCadastroBarcoLayout = new javax.swing.GroupLayout(paneOptionCadastroBarco);
        paneOptionCadastroBarco.setLayout(paneOptionCadastroBarcoLayout);
        paneOptionCadastroBarcoLayout.setHorizontalGroup(
            paneOptionCadastroBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOptionCadastroBarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneInputsBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblTituloBarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paneOptionCadastroBarcoLayout.setVerticalGroup(
            paneOptionCadastroBarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOptionCadastroBarcoLayout.createSequentialGroup()
                .addComponent(lblTituloBarco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneInputsBarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        paneMain.add(paneOptionCadastroBarco, "paneOptionCadastroBarco");
        paneOptionCadastroBarco.getAccessibleContext().setAccessibleName("");

        paneOptionCadastroRota.setBackground(new java.awt.Color(50, 7, 88));

        lblTituloRota.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTituloRota.setForeground(new java.awt.Color(255, 96, 83));
        lblTituloRota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRota.setText("Cadastrar Rota");

        paneInputsRota.setBackground(new java.awt.Color(59, 12, 108));

        lblValorRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblValorRota.setForeground(new java.awt.Color(255, 255, 255));
        lblValorRota.setText("Valor");

        txtValorRota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtValorRota.setForeground(new java.awt.Color(0, 0, 0));
        txtValorRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtValorRota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorRotaKeyTyped(evt);
            }
        });

        txtOrigemRota.setEditable(false);
        txtOrigemRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtOrigemRota.setForeground(new java.awt.Color(0, 0, 0));
        txtOrigemRota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblOrigemRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblOrigemRota.setForeground(new java.awt.Color(255, 255, 255));
        lblOrigemRota.setText("Origem");

        txtDestinoRota.setEditable(false);
        txtDestinoRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDestinoRota.setForeground(new java.awt.Color(0, 0, 0));
        txtDestinoRota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblDestinoRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDestinoRota.setForeground(new java.awt.Color(255, 255, 255));
        lblDestinoRota.setText("Destino");

        jcbDestino.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcbDestino.setForeground(new java.awt.Color(0, 0, 0));
        jcbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcbDestino.setAutoscrolls(true);
        jcbDestino.setBorder(null);
        jcbDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbDestinoItemStateChanged(evt);
            }
        });

        jcbOrigem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcbOrigem.setForeground(new java.awt.Color(0, 0, 0));
        jcbOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcbOrigem.setAutoscrolls(true);
        jcbOrigem.setBorder(null);
        jcbOrigem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbOrigemItemStateChanged(evt);
            }
        });

        lblCategoriaRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCategoriaRota.setForeground(java.awt.SystemColor.textHighlightText);
        lblCategoriaRota.setText("Categoria");

        txtCategoriaRota.setEditable(false);
        txtCategoriaRota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCategoriaRota.setForeground(new java.awt.Color(0, 0, 0));
        txtCategoriaRota.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jcbCategoria.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jcbCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcbCategoria.setAutoscrolls(true);
        jcbCategoria.setBorder(null);
        jcbCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCategoriaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout paneInputsRotaLayout = new javax.swing.GroupLayout(paneInputsRota);
        paneInputsRota.setLayout(paneInputsRotaLayout);
        paneInputsRotaLayout.setHorizontalGroup(
            paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsRotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategoriaRota, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDestinoRota, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addComponent(lblValorRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblOrigemRota, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOrigemRota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(txtDestinoRota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(txtValorRota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaRota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbOrigem, 0, 184, Short.MAX_VALUE)
                    .addComponent(jcbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneInputsRotaLayout.setVerticalGroup(
            paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsRotaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValorRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValorRota, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigemRota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrigemRota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestinoRota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestinoRota, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaRota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaRota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneOptionCadastroRotaLayout = new javax.swing.GroupLayout(paneOptionCadastroRota);
        paneOptionCadastroRota.setLayout(paneOptionCadastroRotaLayout);
        paneOptionCadastroRotaLayout.setHorizontalGroup(
            paneOptionCadastroRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addGroup(paneOptionCadastroRotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneInputsRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneOptionCadastroRotaLayout.setVerticalGroup(
            paneOptionCadastroRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOptionCadastroRotaLayout.createSequentialGroup()
                .addComponent(lblTituloRota, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneInputsRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        paneMain.add(paneOptionCadastroRota, "paneOptionCadastroRota");

        paneOptionCadastroCidade.setBackground(new java.awt.Color(50, 7, 88));

        lblTituloCidade.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTituloCidade.setForeground(new java.awt.Color(255, 96, 83));
        lblTituloCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCidade.setText("Cadastrar Cidade");

        paneInputsCidade.setBackground(new java.awt.Color(59, 12, 108));

        lblEstadoCidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEstadoCidade.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoCidade.setText("Estado");

        lblCidadeCidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCidadeCidade.setForeground(new java.awt.Color(255, 255, 255));
        lblCidadeCidade.setText("Cidade");

        txtEstadoCidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEstadoCidade.setForeground(new java.awt.Color(0, 0, 0));
        txtEstadoCidade.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEstadoCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoCidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoCidadeKeyTyped(evt);
            }
        });

        txtCidadeCidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCidadeCidade.setForeground(new java.awt.Color(0, 0, 0));
        txtCidadeCidade.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCidadeCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeCidadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout paneInputsCidadeLayout = new javax.swing.GroupLayout(paneInputsCidade);
        paneInputsCidade.setLayout(paneInputsCidadeLayout);
        paneInputsCidadeLayout.setHorizontalGroup(
            paneInputsCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneInputsCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoCidade)
                    .addComponent(lblCidadeCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstadoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneInputsCidadeLayout.setVerticalGroup(
            paneInputsCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsCidadeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneInputsCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstadoCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblEstadoCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneInputsCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCidadeCidade)
                    .addComponent(lblCidadeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout paneOptionCadastroCidadeLayout = new javax.swing.GroupLayout(paneOptionCadastroCidade);
        paneOptionCadastroCidade.setLayout(paneOptionCadastroCidadeLayout);
        paneOptionCadastroCidadeLayout.setHorizontalGroup(
            paneOptionCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addGroup(paneOptionCadastroCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneInputsCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneOptionCadastroCidadeLayout.setVerticalGroup(
            paneOptionCadastroCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOptionCadastroCidadeLayout.createSequentialGroup()
                .addComponent(lblTituloCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneInputsCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 214, Short.MAX_VALUE))
        );

        paneMain.add(paneOptionCadastroCidade, "paneOptionCadastroCidade");

        paneOptionCadastroCategoria.setBackground(new java.awt.Color(50, 7, 88));

        lblTituloCategoria.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTituloCategoria.setForeground(new java.awt.Color(255, 96, 83));
        lblTituloCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCategoria.setText("Cadastrar Categoria");

        paneInputsCategoria.setBackground(new java.awt.Color(59, 12, 108));

        lblNomeCategoria.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeCategoria.setForeground(java.awt.SystemColor.textHighlightText);
        lblNomeCategoria.setText("Nome");

        txtNomeCategoria.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomeCategoria.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNomeCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeCategoriaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout paneInputsCategoriaLayout = new javax.swing.GroupLayout(paneInputsCategoria);
        paneInputsCategoria.setLayout(paneInputsCategoriaLayout);
        paneInputsCategoriaLayout.setHorizontalGroup(
            paneInputsCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        paneInputsCategoriaLayout.setVerticalGroup(
            paneInputsCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInputsCategoriaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(paneInputsCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneOptionCadastroCategoriaLayout = new javax.swing.GroupLayout(paneOptionCadastroCategoria);
        paneOptionCadastroCategoria.setLayout(paneOptionCadastroCategoriaLayout);
        paneOptionCadastroCategoriaLayout.setHorizontalGroup(
            paneOptionCadastroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneOptionCadastroCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneInputsCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneOptionCadastroCategoriaLayout.setVerticalGroup(
            paneOptionCadastroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOptionCadastroCategoriaLayout.createSequentialGroup()
                .addComponent(lblTituloCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneInputsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 237, Short.MAX_VALUE))
        );

        paneMain.add(paneOptionCadastroCategoria, "paneOptionCadastroCategoria");

        paneRodape.setBackground(new java.awt.Color(50, 35, 150));

        btnVoltar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 96, 83));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnVoltar.setBorderPainted(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 96, 83));
        btnCadastrar.setText("Cadastar");
        btnCadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneRodapeLayout = new javax.swing.GroupLayout(paneRodape);
        paneRodape.setLayout(paneRodapeLayout);
        paneRodapeLayout.setHorizontalGroup(
            paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );
        paneRodapeLayout.setVerticalGroup(
            paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRodapeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // EVENTOS
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            if(paneOptionCadastroBarco.isVisible()){
                // BARCO
                RegistraDados regBarco = new RegistraDados();
                regBarco.registraBarco(txtNomeBarco, txtCapacidadeBarco);
            }else if(paneOptionCadastroRota.isVisible()){
                // ROTA
                RegistraDados regRota = new RegistraDados();
                regRota.registraRota(txtValorRota, txtOrigemRota, txtDestinoRota, txtCategoriaRota);
            }else if(paneOptionCadastroCidade.isVisible()){
                // CIDADE
                RegistraDados regCidade = new RegistraDados();
                regCidade.registraCidade(txtEstadoCidade, txtCidadeCidade);
            }else if(paneOptionCadastroCategoria.isVisible()){
                // CATEGORIA
                RegistraDados regCategoria = new RegistraDados();
                regCategoria.registrarCategoria(txtNomeCategoria);
            }  
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Não foi possível executar os métodos de registros", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaDeRegistro telaReg = new TelaDeRegistro();
        this.dispose();
        telaReg.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    // VALIDAR PARA QUE SOMENTE ACEITE NUMEROS, EM UM EVENTO QUANDO A TECLA FOR PRESIONADA
    private void txtCapacidadeBarcoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadeBarcoKeyTyped
        new ValideCampoText().validaCamposComNumero(evt);
    }//GEN-LAST:event_txtCapacidadeBarcoKeyTyped

    private void txtNomeBarcoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeBarcoKeyTyped
        new RestringeCampoText().restringirCampoDeNumeroEspecial(evt);
    }//GEN-LAST:event_txtNomeBarcoKeyTyped

    private void txtEstadoCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCidadeKeyTyped
        new RestringeCampoText().restringirCampoDeNumeroEspecial(evt);
        new ValideCampoText().validaCampoEstado(evt, txtEstadoCidade);
    }//GEN-LAST:event_txtEstadoCidadeKeyTyped

    private void txtCidadeCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeCidadeKeyTyped
       new RestringeCampoText().restringirCampoDeNumeroEspecial(evt);
    }//GEN-LAST:event_txtCidadeCidadeKeyTyped

    private void txtEstadoCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCidadeKeyReleased
        txtEstadoCidade.setText(txtEstadoCidade.getText().toUpperCase());
    }//GEN-LAST:event_txtEstadoCidadeKeyReleased

    private void jcbDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbDestinoItemStateChanged
        if(!jcbDestino.getSelectedItem().toString().equalsIgnoreCase("selecione") ){
            if(jcbDestino.getSelectedItem().toString().equalsIgnoreCase(jcbOrigem.getSelectedItem().toString())){      
                txtDestinoRota.setText("");
                JOptionPane.showMessageDialog(null, "Essa cidade está selecionada", "Atenção", JOptionPane.WARNING_MESSAGE);
            }else{
                txtDestinoRota.setText(jcbDestino.getSelectedItem().toString());
            }
        }else{
            txtDestinoRota.setText("");
        }
    }//GEN-LAST:event_jcbDestinoItemStateChanged

    private void jcbOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbOrigemItemStateChanged
        if(!jcbOrigem.getSelectedItem().toString().equalsIgnoreCase("selecione")){
            if(jcbOrigem.getSelectedItem().toString().equalsIgnoreCase(jcbDestino.getSelectedItem().toString())){                
                txtOrigemRota.setText("");
                JOptionPane.showMessageDialog(null, "Essa cidade está selecionada", "Atenção", JOptionPane.WARNING_MESSAGE);
            }else{
                txtOrigemRota.setText(jcbOrigem.getSelectedItem().toString());
            }
        }else{
            txtOrigemRota.setText("");
        }
    }//GEN-LAST:event_jcbOrigemItemStateChanged

    private void txtValorRotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRotaKeyTyped
        new ValideCampoText().validaCamposComNumero(evt);
    }//GEN-LAST:event_txtValorRotaKeyTyped

    private void txtNomeCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCategoriaKeyTyped
        new RestringeCampoText().restringirCampoDeNumeroEspecial(evt);
    }//GEN-LAST:event_txtNomeCategoriaKeyTyped

    private void jcbCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCategoriaItemStateChanged
        if(!jcbCategoria.getSelectedItem().toString().equalsIgnoreCase("selecione")){
            txtCategoriaRota.setText(jcbCategoria.getSelectedItem().toString());
        }else{
            txtCategoriaRota.setText("");
        }        
    }//GEN-LAST:event_jcbCategoriaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCadastrar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbDestino;
    private javax.swing.JComboBox<String> jcbOrigem;
    private javax.swing.JLabel lblCapacidadeBarco;
    private javax.swing.JLabel lblCategoriaRota;
    private javax.swing.JLabel lblCidadeCidade;
    private javax.swing.JLabel lblDestinoRota;
    private javax.swing.JLabel lblEstadoCidade;
    private javax.swing.JLabel lblNomeBarco;
    private javax.swing.JLabel lblNomeCategoria;
    private javax.swing.JLabel lblOrigemRota;
    private javax.swing.JLabel lblTituloBarco;
    private javax.swing.JLabel lblTituloCategoria;
    private javax.swing.JLabel lblTituloCidade;
    private javax.swing.JLabel lblTituloRota;
    private javax.swing.JLabel lblValorRota;
    private javax.swing.JPanel paneInputsBarco;
    private javax.swing.JPanel paneInputsCategoria;
    private javax.swing.JPanel paneInputsCidade;
    private javax.swing.JPanel paneInputsRota;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPanel paneOptionCadastroBarco;
    private javax.swing.JPanel paneOptionCadastroCategoria;
    private javax.swing.JPanel paneOptionCadastroCidade;
    private javax.swing.JPanel paneOptionCadastroRota;
    private javax.swing.JPanel paneRodape;
    private javax.swing.JTextField txtCapacidadeBarco;
    private javax.swing.JTextField txtCategoriaRota;
    private javax.swing.JTextField txtCidadeCidade;
    private javax.swing.JTextField txtDestinoRota;
    private javax.swing.JTextField txtEstadoCidade;
    private javax.swing.JTextField txtNomeBarco;
    private javax.swing.JTextField txtNomeCategoria;
    private javax.swing.JTextField txtOrigemRota;
    private javax.swing.JFormattedTextField txtValorRota;
    // End of variables declaration//GEN-END:variables
}
