package esbam.canoa123.views;

// CLASSES (ESBAM)
import esbam.canoa123.controll.CidadesController;
import esbam.canoa123.controll.PassageirosController;
import esbam.canoa123.controll.RotasController;
import esbam.canoa123.views.telacadastroviews.TelaDeRegistro;
import esbam.canoa123.views.tablesviews.TabelaBarcos;
import esbam.canoa123.views.tablesviews.TabelaCidades;
import esbam.canoa123.views.tablesviews.TabelaPassageiros;
import esbam.canoa123.views.telaviagemviews.TelaViagem;
import esbam.canoa123.controll.dao.conexao.ConnectionMVC;
import esbam.canoa123.controll.bussines.FormataCamposMask;
import esbam.canoa123.controll.bussines.RestringeCampoText;
import esbam.canoa123.controll.bussines.ValideCampoText;
import esbam.canoa123.register.RegistraDados;
import esbam.canoa123.model.Rotas;
import esbam.canoa123.views.telaloginviews.TelaLogin;
import esbam.canoa123.controll.UsuariosController;
import esbam.canoa123.model.Cidades;

// CLASSES (JAVA)
import java.awt.image.BufferedImage;
import java.text.DateFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 * Classe que exibirá a tela principal do sistema. As manipulações começará pela
 * esta classe.
 *
 * @author Jonny Nunes Viana
 */
public class TelaPrincipal extends javax.swing.JFrame {
    java.sql.Connection con;
    
    // JANELAS
    TabelaBarcos tb;
    TabelaPassageiros tp;
    TabelaCidades tc;

    public TelaPrincipal() {
        initComponents();
        executarComp();
        inicializa();
        setData();
        formatarCampo();
        verificaUserAcesso();
    }

    // *************************************************************************************
    // INICIALIZADORES
    /**
     * Métedos para inicializar alguns componentes da interface e inicializar as
     * entradas de dados inicial.
     */
    private void executarComp() {
        lblImgBanco.setText("");
        txtIdPessoa.setText((new PassageirosController().ultimoID() == null) ? "vazio" : Integer.toString(new PassageirosController().ultimoID().getId() + 1)); // TERNÁRIO
    }
    
    /**
     * Método para verificar quem tem o acesso ou quem acessou a tela.
     * Para saber quem está com acesso, se é um adm ou um user, o valor de acesso tem que
     * ser igual a true. E assim modificar as restrição de acordo com a regra de negócio,
     * que diz a respetio que user não poder acessar o menu de relatório e cliente, diferente 
     * do adm que tem o acesso desses menus.
     */
    private void verificaUserAcesso(){
        UsuariosController user = new UsuariosController();
        if(user.verificaAcessoUsuario(true).getPerfil().equalsIgnoreCase("user")){
            // USER
            lblUsuario.setText("Usuário: " + user.verificaAcessoUsuario(true).getNome());
            this.menuRelatorios.setEnabled(false);
            this.menuClientes.setEnabled(false);
        }else{
            // ADM
            lblUsuario.setText("Administrador: " + user.verificaAcessoUsuario(true).getNome());
            this.menuRelatorios.setEnabled(true);
            this.menuClientes.setEnabled(true);
        }
    }

    /**
     * Método para inicializar a sessão (conexão) ao banco de dados. Além disso,
     * inicializando a imagem do banco no rodapé.
     */
    private void inicializa() {
        restabeleceConexao(); // CONECTANDO O BANCO
        verificaBancoDeDados(con); // SE O BANCO FOR CONECTADO, APARECE UMA IMAGEM POSITIVO DO BANCO
    }

    /**
     * Método para inicializar a data atual no rodapé.
     */
    private void setData() {
        java.util.Date data = new java.util.Date(); // DATA LOCAL (SYSTEM)
        java.text.DateFormat formt = DateFormat.getDateInstance(DateFormat.FULL); // FORMATAÇÃO DA DATA, A CONSTANTE FULL E A DATA COMPLETA
        lblData.setText("Data: " + formt.format(data));
    }

    /**
     * Método para colocar a formatação ao campos espectivos. Por exemplo: o
     * campo CPF.
     */
    private void formatarCampo() {
        try {
            new FormataCamposMask().fieldCPF(txtCpfPessoa);
            new FormataCamposMask().fieldData(txtDataPassagem);
        } catch (ParseException ex) {
            throw new Error("Erro ao formatar os campos cpf e data");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttGroupSexo = new javax.swing.ButtonGroup();
        paneMain = new javax.swing.JPanel();
        paneRodape = new javax.swing.JPanel();
        lblImgBanco = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtNomePessoa = new javax.swing.JTextField();
        paneImgPessoa = new javax.swing.JPanel();
        lblImgPessoa = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtIdPessoa = new javax.swing.JTextField();
        paneSexo = new javax.swing.JPanel();
        jrdFeminino = new javax.swing.JRadioButton();
        jrdMasculino = new javax.swing.JRadioButton();
        txtCpfPessoa = new javax.swing.JFormattedTextField();
        txtTelefonePessoa = new javax.swing.JFormattedTextField();
        panePassagem = new javax.swing.JPanel();
        lblOrigem = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        txtOrigem = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnBuscaRota = new javax.swing.JButton();
        txtDataPassagem = new javax.swing.JFormattedTextField();
        lblDataCompra = new javax.swing.JLabel();
        paneDesktopTabela = new javax.swing.JDesktopPane();
        btnSalvar = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        barMenus = new javax.swing.JMenuBar();
        menuRegistro = new javax.swing.JMenu();
        mnResgistrar = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuTelaBarcos = new javax.swing.JMenuItem();
        menuTelaPassageiros = new javax.swing.JMenuItem();
        menuTelaCidades = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuViagem = new javax.swing.JMenu();
        menuAgendados = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        paneMain.setBackground(new java.awt.Color(60, 14, 64));
        paneMain.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do passageiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), java.awt.SystemColor.textHighlightText)); // NOI18N

        paneRodape.setBackground(new java.awt.Color(4, 81, 65));

        lblImgBanco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImgBanco.setForeground(java.awt.SystemColor.text);
        lblImgBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgBanco.setText("BD");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblData.setForeground(java.awt.SystemColor.text);
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblData.setText("DATA");
        lblData.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(java.awt.SystemColor.text);
        lblUsuario.setText("USER");

        javax.swing.GroupLayout paneRodapeLayout = new javax.swing.GroupLayout(paneRodape);
        paneRodape.setLayout(paneRodapeLayout);
        paneRodapeLayout.setHorizontalGroup(
            paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(lblImgBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneRodapeLayout.setVerticalGroup(
            paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lblImgBanco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNome.setForeground(java.awt.SystemColor.textHighlightText);
        lblNome.setText("Nome");

        lblCPF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCPF.setForeground(java.awt.SystemColor.textHighlightText);
        lblCPF.setText("CPF");

        lblTelefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTelefone.setForeground(java.awt.SystemColor.textHighlightText);
        lblTelefone.setText("Telefone");

        txtNomePessoa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomePessoa.setForeground(new java.awt.Color(0, 0, 0));
        txtNomePessoa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNomePessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNomePessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomePessoaKeyTyped(evt);
            }
        });

        paneImgPessoa.setBackground(new java.awt.Color(204, 204, 204));
        paneImgPessoa.setName("paneImgPessoa"); // NOI18N

        lblImgPessoa.setForeground(new java.awt.Color(0, 0, 0));
        lblImgPessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgPessoa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout paneImgPessoaLayout = new javax.swing.GroupLayout(paneImgPessoa);
        paneImgPessoa.setLayout(paneImgPessoaLayout);
        paneImgPessoaLayout.setHorizontalGroup(
            paneImgPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneImgPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneImgPessoaLayout.setVerticalGroup(
            paneImgPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneImgPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblID.setForeground(java.awt.SystemColor.textHighlightText);
        lblID.setText("ID");

        txtIdPessoa.setEditable(false);
        txtIdPessoa.setBackground(new java.awt.Color(19, 50, 114));
        txtIdPessoa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtIdPessoa.setForeground(java.awt.SystemColor.textHighlightText);
        txtIdPessoa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdPessoa.setText("0");
        txtIdPessoa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttGroupSexo.add(jrdFeminino);
        jrdFeminino.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrdFeminino.setForeground(java.awt.SystemColor.textText);
        jrdFeminino.setText("Feminino");
        jrdFeminino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jrdFeminino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrdFeminino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrdFemininoMouseClicked(evt);
            }
        });

        buttGroupSexo.add(jrdMasculino);
        jrdMasculino.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jrdMasculino.setForeground(java.awt.SystemColor.textText);
        jrdMasculino.setText("Masculino");
        jrdMasculino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jrdMasculino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jrdMasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrdMasculinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneSexoLayout = new javax.swing.GroupLayout(paneSexo);
        paneSexo.setLayout(paneSexoLayout);
        paneSexoLayout.setHorizontalGroup(
            paneSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrdFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jrdMasculino)
                .addContainerGap())
        );
        paneSexoLayout.setVerticalGroup(
            paneSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneSexoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdFeminino)
                    .addComponent(jrdMasculino))
                .addContainerGap())
        );

        txtCpfPessoa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCpfPessoa.setForeground(new java.awt.Color(0, 0, 0));
        txtCpfPessoa.setText("  ");
        txtCpfPessoa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtTelefonePessoa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtTelefonePessoa.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonePessoa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelefonePessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonePessoaKeyTyped(evt);
            }
        });

        panePassagem.setBackground(new java.awt.Color(60, 14, 78));
        panePassagem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Passagem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), java.awt.SystemColor.textHighlightText)); // NOI18N

        lblOrigem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblOrigem.setForeground(java.awt.SystemColor.textHighlightText);
        lblOrigem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOrigem.setText("Origem");

        lblDestino.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDestino.setForeground(java.awt.SystemColor.textHighlightText);
        lblDestino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDestino.setText("Destino");

        lblValor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblValor.setForeground(java.awt.SystemColor.textHighlightText);
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValor.setText("Valor");

        txtDestino.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtDestino.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDestinoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDestinoKeyTyped(evt);
            }
        });

        txtOrigem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtOrigem.setForeground(new java.awt.Color(0, 0, 0));
        txtOrigem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtOrigem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrigemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOrigemKeyTyped(evt);
            }
        });

        txtValor.setEditable(false);
        txtValor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtValor.setForeground(new java.awt.Color(0, 0, 0));
        txtValor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnBuscaRota.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnBuscaRota.setForeground(new java.awt.Color(255, 96, 83));
        btnBuscaRota.setText("Buscar");
        btnBuscaRota.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnBuscaRota.setBorderPainted(false);
        btnBuscaRota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscaRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaRotaActionPerformed(evt);
            }
        });

        txtDataPassagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDataPassagem.setForeground(new java.awt.Color(0, 0, 0));
        txtDataPassagem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblDataCompra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDataCompra.setForeground(java.awt.SystemColor.textHighlightText);
        lblDataCompra.setText("Data");

        javax.swing.GroupLayout panePassagemLayout = new javax.swing.GroupLayout(panePassagem);
        panePassagem.setLayout(panePassagemLayout);
        panePassagemLayout.setHorizontalGroup(
            panePassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePassagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtValor)
                    .addComponent(lblOrigem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtOrigem, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(panePassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscaRota, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panePassagemLayout.setVerticalGroup(
            panePassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePassagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigem)
                    .addComponent(lblDataCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDataPassagem)
                    .addComponent(txtOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(lblDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panePassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panePassagemLayout.createSequentialGroup()
                        .addComponent(btnBuscaRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDesktopTabela.setBackground(new java.awt.Color(60, 14, 64));

        javax.swing.GroupLayout paneDesktopTabelaLayout = new javax.swing.GroupLayout(paneDesktopTabela);
        paneDesktopTabela.setLayout(paneDesktopTabelaLayout);
        paneDesktopTabelaLayout.setHorizontalGroup(
            paneDesktopTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paneDesktopTabelaLayout.setVerticalGroup(
            paneDesktopTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnSalvar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 96, 83));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSalvar.setBorderPainted(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 96, 83));
        btnLogout.setText("logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnLogout.setBorderPainted(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paneImgPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCpfPessoa)
                                .addComponent(txtTelefonePessoa)
                                .addComponent(txtNomePessoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panePassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paneDesktopTabela)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCpfPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(paneSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paneImgPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(panePassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paneDesktopTabela))
                .addGap(17, 17, 17)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(paneRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        barMenus.setBackground(new java.awt.Color(4, 81, 65));
        barMenus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        barMenus.setBorderPainted(false);

        menuRegistro.setForeground(new java.awt.Color(18, 238, 247));
        menuRegistro.setText("Registro");
        menuRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRegistro.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N

        mnResgistrar.setText("Registrar");
        mnResgistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnResgistrarActionPerformed(evt);
            }
        });
        menuRegistro.add(mnResgistrar);

        barMenus.add(menuRegistro);

        menuRelatorios.setForeground(new java.awt.Color(18, 238, 247));
        menuRelatorios.setText("Relatório");
        menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelatorios.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N

        menuTelaBarcos.setText("Barcos");
        menuTelaBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTelaBarcosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuTelaBarcos);

        menuTelaPassageiros.setText("Passageiros");
        menuTelaPassageiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTelaPassageirosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuTelaPassageiros);

        menuTelaCidades.setText("Cidades");
        menuTelaCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTelaCidadesActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuTelaCidades);

        barMenus.add(menuRelatorios);

        menuClientes.setForeground(new java.awt.Color(18, 238, 247));
        menuClientes.setText("Clientes");
        menuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuClientes.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        barMenus.add(menuClientes);

        menuViagem.setForeground(new java.awt.Color(18, 238, 247));
        menuViagem.setText("Viagem");
        menuViagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuViagem.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N

        menuAgendados.setText("Agendados");
        menuAgendados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendadosActionPerformed(evt);
            }
        });
        menuViagem.add(menuAgendados);

        barMenus.add(menuViagem);

        menuAjuda.setForeground(new java.awt.Color(18, 238, 247));
        menuAjuda.setText("Ajuda");
        menuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAjuda.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        barMenus.add(menuAjuda);

        setJMenuBar(barMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // *************************************************************************************
    // EVENTOS DE COMPONENTES
    /**
     * Evento performado ao submenu do menu bar. O submenu desse evento é o
     * "Registrar".
     *
     * @param evt Um objeto da classe de evento ActionEvent.
     */
    private void mnResgistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnResgistrarActionPerformed
        TelaDeRegistro tableReg = new TelaDeRegistro();
        tableReg.setVisible(true);
        fechaConexao(con);
        this.dispose();
    }//GEN-LAST:event_mnResgistrarActionPerformed

    /**
     * Evento de entrada de dados do teclado. Ao adentrar com a digitalização de
     * um tecla será disparado um evento. Nela é chamado um método
     * "restringirCampoDeNumeroEspecial()" para bloquear a entrada de dados de
     * número e caracteres especiais.
     *
     * @param evt Um objeto da classe de evento ActionEvent.
     */
    private void txtNomePessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomePessoaKeyTyped
        new RestringeCampoText().restringirCampoDeNumeroEspecial(evt);
    }//GEN-LAST:event_txtNomePessoaKeyTyped

    /**
     * Evento performado ao botão sobre o salavamento dos dados. Nela será
     * chamados outros métodos e classes para o resgistro dos dados de entradas.
     *
     * @param evt Um objeto da classe de evento ActionEvent.
     */
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        RegistraDados reg = new RegistraDados();
        try {
            if (reg.registraPassageiro(txtNomePessoa,sexoSelecionado(),txtCpfPessoa,txtTelefonePessoa,txtOrigem,txtDestino,txtValor,txtDataPassagem)) {
                limpaCampos();
            } 
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Não foi possível executar o registraPassageiro()", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtOrigemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrigemKeyTyped
        new RestringeCampoText().restringirCampoDeNumeroEspecial(evt);
    }//GEN-LAST:event_txtOrigemKeyTyped

    private void txtDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoKeyTyped
        new RestringeCampoText().restringirCampoDeNumeroEspecial(evt);
    }//GEN-LAST:event_txtDestinoKeyTyped

    private void txtTelefonePessoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonePessoaKeyTyped
        new ValideCampoText().validaCamposComNumero(evt);
        new ValideCampoText().validaCampoTelefone(evt, txtTelefonePessoa);
    }//GEN-LAST:event_txtTelefonePessoaKeyTyped

    private void menuTelaBarcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTelaBarcosActionPerformed
        if (tb == null || !tb.isVisible()) {
            tb = new TabelaBarcos();
            tb.setVisible(true);
            paneDesktopTabela.add(tb);
        }
    }//GEN-LAST:event_menuTelaBarcosActionPerformed

    private void menuTelaPassageirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTelaPassageirosActionPerformed
        if (tp == null || !tp.isVisible()) {
            tp = new TabelaPassageiros();
            tp.setVisible(true);
            paneDesktopTabela.add(tp);
        }
    }//GEN-LAST:event_menuTelaPassageirosActionPerformed

    private void btnBuscaRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaRotaActionPerformed
        buscaRota();
    }//GEN-LAST:event_btnBuscaRotaActionPerformed

    private void txtDestinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinoKeyReleased
        nomeProprio(txtDestino);
    }//GEN-LAST:event_txtDestinoKeyReleased

    private void txtOrigemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrigemKeyReleased
        nomeProprio(txtOrigem);
    }//GEN-LAST:event_txtOrigemKeyReleased

    private void menuTelaCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTelaCidadesActionPerformed
        if (tc == null || !tc.isVisible()) {
            tc = new TabelaCidades();
            tc.setVisible(true);
            paneDesktopTabela.add(tc);
        }
    }//GEN-LAST:event_menuTelaCidadesActionPerformed

    private void menuAgendadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendadosActionPerformed
        TelaViagem telV = new TelaViagem();
        telV.setVisible(true);
        fechaConexao(con);
        this.dispose();
    }//GEN-LAST:event_menuAgendadosActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        TelaLogin telLogin = new TelaLogin();
        telLogin.setVisible(true);
        fechaConexao(con);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jrdMasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrdMasculinoMouseClicked
        mudaImgGenero();
    }//GEN-LAST:event_jrdMasculinoMouseClicked

    private void jrdFemininoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrdFemininoMouseClicked
        mudaImgGenero();
    }//GEN-LAST:event_jrdFemininoMouseClicked

    // *************************************************************************************
    // PRINCIPAL
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // *************************************************************************************
    // VERIFICADORES
    
    /**
     * 
     * @param conn
     * @return 
     */
    private boolean verificaBancoDeDados(java.sql.Connection conn) {
        javax.swing.ImageIcon img = new javax.swing.ImageIcon();
        try {
            if (conn == null || conn.isValid(2) == false) {
                img.setImage(altDimen("bancoNegativo", lblImgBanco));
                lblImgBanco.setIcon(img);
                lblImgBanco.updateUI();
                return false;
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            throw new RuntimeException("Banco de dados não conctado");
        }
        if (conn != null) {
            img.setImage(altDimen("bancoPositivo", lblImgBanco));
            lblImgBanco.setIcon(img);
            lblImgBanco.updateUI();
            return true;
        }
        return false;
    }

    // *************************************************************************************
    // MODIFICADORES
    
    /**
     * 
     * @param nomeImg
     * @param lbl
     * @return 
     */
    private java.awt.Image altDimen(String nomeImg, javax.swing.JLabel lbl) {
        BufferedImage img = null;
        try {
            img = javax.imageio.ImageIO.read(new java.io.File(String.format("C:\\Projetos\\Gerecionamento\\Canoa123\\src\\esbam\\canoa123\\img\\%s.png", nomeImg)));
        } catch (java.io.IOException ex) {
            lbl.setAlignmentX(CENTER_ALIGNMENT);
            lbl.setAlignmentY(CENTER_ALIGNMENT);
            lbl.setText("<html>Erro ao carregar imagem</html>");
            return null;
        }
        java.awt.Image imageDimensionada = img.getScaledInstance(lbl.getWidth() - 5, lbl.getHeight() - 5, java.awt.Image.SCALE_SMOOTH);
        return imageDimensionada;
    }
    
    /**
     * 
     * @param text 
     */
    private void nomeProprio(javax.swing.JTextField text){
        if(!text.getText().isEmpty()){
            if(text.getText().length() < 2 || !text.getText().substring(0, 1).equals(text.getText().substring(0, 1).toUpperCase())){
                text.setText(text.getText().substring(0, 1).toUpperCase());
            }  
        }
    }    
    
    /**
     * Método para limpas os campos ao registrar um passageiro.
     */
    private void limpaCampos() {
        txtNomePessoa.setText("");
        txtNomePessoa.requestFocus();
        txtCpfPessoa.setText("");
        txtTelefonePessoa.setText("");
        jrdFeminino.setSelected(false);
        jrdFeminino.updateUI();
        jrdMasculino.setSelected(false);
        jrdMasculino.updateUI();
        lblImgPessoa.setIcon(null);
        lblImgPessoa.updateUI();
        txtDestino.setText("");
        txtOrigem.setText("");
        txtValor.setText("");
        txtDataPassagem.setText("");
        txtIdPessoa.setText(Integer.toString(new PassageirosController().ultimoID().getId() + 1));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenus;
    private javax.swing.JButton btnBuscaRota;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttGroupSexo;
    private javax.swing.JRadioButton jrdFeminino;
    private javax.swing.JRadioButton jrdMasculino;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataCompra;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImgBanco;
    private javax.swing.JLabel lblImgPessoa;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblValor;
    private javax.swing.JMenuItem menuAgendados;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuTelaBarcos;
    private javax.swing.JMenuItem menuTelaCidades;
    private javax.swing.JMenuItem menuTelaPassageiros;
    private javax.swing.JMenu menuViagem;
    private javax.swing.JMenuItem mnResgistrar;
    private javax.swing.JDesktopPane paneDesktopTabela;
    private javax.swing.JPanel paneImgPessoa;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPanel panePassagem;
    private javax.swing.JPanel paneRodape;
    private javax.swing.JPanel paneSexo;
    private javax.swing.JFormattedTextField txtCpfPessoa;
    private javax.swing.JFormattedTextField txtDataPassagem;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtIdPessoa;
    private javax.swing.JTextField txtNomePessoa;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JFormattedTextField txtTelefonePessoa;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    // *************************************************************************************
    // METODOS
    
    /**
     * 
     * @return 
     */
    private String sexoSelecionado(){
        String sexo = (jrdMasculino.isSelected()) ? jrdMasculino.getText() : (jrdFeminino.isSelected()) ? jrdFeminino.getText() : "";
        return sexo;
    }
    
    /**
     * 
     * @param conn 
     */
    private void fechaConexao(java.sql.Connection conn){ new esbam.canoa123.controll.dao.conexao.ConnectionMVC().closeConnection(conn); }
    
    /**
     * Método para restabelecer a conexão ao banco. Se por acaso for utilizado
     * em um método para estabelecer novamente a conexão.
     */
    private void restabeleceConexao() { con = new ConnectionMVC().getConnetion(); }
    
    /**
     * 
     */
    private void buscaRota(){
        String origem = txtOrigem.getText();
        String destino = txtDestino.getText();
        Cidades cidadeOrigem = new CidadesController().buscaLocalidade(origem);
        Cidades cidadeDestino = new CidadesController().buscaLocalidade(destino);
        if(cidadeOrigem == null || cidadeDestino == null){
            txtValor.setText("");
            JOptionPane.showMessageDialog(this, "Cidades não encontrada!", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Rotas rota = new RotasController().buscaOrigemDestino(cidadeOrigem, cidadeDestino);
        if(rota != null){
            txtValor.setText(String.valueOf(rota.getValor()));
        }else{
            txtValor.setText("");
            JOptionPane.showMessageDialog(this, "Rota não encontrada!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * 
     */
    private void mudaImgGenero(){
        javax.swing.ImageIcon img = new javax.swing.ImageIcon();
        if (jrdMasculino.isSelected()) {
            img.setImage(altDimen("avtMasculino", lblImgPessoa));
            lblImgPessoa.setIcon(img);
            lblImgPessoa.updateUI();
        } else if (jrdFeminino.isSelected()) {
            img.setImage(altDimen("avtFeminino", lblImgPessoa));
            lblImgPessoa.setIcon(img);
            lblImgPessoa.updateUI();
        } else {
            lblImgPessoa.setIcon(img);
            lblImgPessoa.updateUI();
        }
    }
}